--liquibase formatted sql
--changeset ugundeti:20180515T1058266323 runAlways:true logicalFilepath:SQL_Liquibase_ASE\procs\framework.dbo.arch_util_sqlinj_cleanser.sql
/* Script generated by dbschema.pl(2.4.2) on Wed Sep  6 13:47:23 2006.  */

use framework
go
--changeset ugundeti:20180515T1058266479 runAlways:true logicalFilepath:SQL_Liquibase_ASE\procs\framework.dbo.arch_util_sqlinj_cleanser.sql
/* Procedure arch_util_sqlinj_cleanser, owner dbo */
IF OBJECT_ID('dbo.arch_util_sqlinj_cleanser') IS NOT NULL
BEGIN

    setuser 'dbo'

    DROP PROCEDURE dbo.arch_util_sqlinj_cleanser

END
go

setuser 'dbo'
go
CREATE PROCEDURE arch_util_sqlinj_cleanser 
(
@dirtyparam varchar(1000) out
)
AS
/*
* 
* Created: 03/28/2006 by Embarcadero Rapid SQL 7.3.0 
* Copyright American Imaging Management 2006
* 
* Procedure Name: arch_util_sqlinj_cleanser
* Create date: 08/08/2006
* Created By: Satinder Jhaj
* 
* Last Update By:   Satinder Jhaj
* Last Updated:     08/08/2006
* 
* Databases Used: none
*
* Tables Used: none
*            
* Description: This stored procedure cleans input parameters from syntax that may 
* be used for sql injection. It should be used by procedures that use dynamic sql where the parameter 
* may have come from an end user
* 
* *********************************************************************/
BEGIN
--Check for ' or " and only take to that position
    DECLARE @pos smallint
    DECLARE @cleanloop bit
    
    SET @cleanloop = 0 -- To force the loop the first time
    
    while @cleanloop = 0
        BEGIN
                SET @cleanloop = 1
                
                IF patindex( "%'%", @dirtyparam ) > 0 -- for ' in a parameter we trucate the string to the '
                        BEGIN
                            SET @dirtyparam = substring(@dirtyparam , 1, patindex( "%'%", @dirtyparam ) - 1)
                            SET @cleanloop = 0
                        END
                IF patindex( '%"%', @dirtyparam ) > 0 -- for " in a parameter we trucate the string to the "
                        BEGIN
                             SET @dirtyparam = substring(@dirtyparam, 1, patindex( '%"%', @dirtyparam ) - 1)
                             SET @cleanloop = 0
                        END
                        
                 SET @pos = charindex( 'SELECT ', UPPER(@dirtyparam)) 
                 IF @pos > 0    
                    BEGIN
                        SET @dirtyparam = LEFT(@dirtyparam,@pos -1 ) + RIGHT(@dirtyparam,LEN(@dirtyparam) - @pos - 6)
                        SET @pos = 0
                        SET @cleanloop = 0
                    END
                
                  SET @pos = charindex( 'INSERT ', UPPER(@dirtyparam)) 
                 IF @pos > 0    
                    BEGIN
                        SET @dirtyparam = LEFT(@dirtyparam,@pos -1 ) + RIGHT(@dirtyparam,LEN(@dirtyparam) - @pos - 6)
                        SET @pos = 0
                        SET @cleanloop = 0
                    END
                
                 SET @pos = charindex( 'UPDATE ', UPPER(@dirtyparam)) 
                 IF @pos > 0    
                    BEGIN
                        SET @dirtyparam = LEFT(@dirtyparam,@pos -1 ) + RIGHT(@dirtyparam,LEN(@dirtyparam) - @pos - 6)
                        SET @pos = 0
                        SET @cleanloop = 0
                    END
            
                  SET @pos = charindex( 'DELETE ', UPPER(@dirtyparam)) 
                 IF @pos > 0    
                    BEGIN
                        SET @dirtyparam = LEFT(@dirtyparam,@pos -1 ) + RIGHT(@dirtyparam,LEN(@dirtyparam) - @pos - 6)
                        SET @pos = 0
                        SET @cleanloop = 0
                    END
                    
                    SET @pos = charindex( 'TRUNCATE ', UPPER(@dirtyparam)) 
                 IF @pos > 0    
                    BEGIN
                        SET @dirtyparam = LEFT(@dirtyparam,@pos -1 ) + RIGHT(@dirtyparam,LEN(@dirtyparam) - @pos - 7)
                        SET @pos = 0
                        SET @cleanloop = 0
                    END
                    
                SET @pos = charindex( 'DROP ', UPPER(@dirtyparam)) 
                 IF @pos > 0    
                    BEGIN
                        SET @dirtyparam = LEFT(@dirtyparam,@pos -1 ) + RIGHT(@dirtyparam,LEN(@dirtyparam) - @pos - 3)
                        SET @pos = 0
                        SET @cleanloop = 0
                    END
                 
                SET @pos = charindex( 'EXEC ', UPPER(@dirtyparam)) 
                 IF @pos > 0    
                    BEGIN
                        SET @dirtyparam = LEFT(@dirtyparam,@pos -1 ) + RIGHT(@dirtyparam,LEN(@dirtyparam) - @pos - 3)
                        SET @pos = 0
                        SET @cleanloop = 0
                    END     
                    
            
                 SET @pos = charindex( 'go ', UPPER(@dirtyparam)) 
                 IF @pos > 0    
                    BEGIN
                        SET @dirtyparam = LEFT(@dirtyparam,@pos -1 ) + RIGHT(@dirtyparam,LEN(@dirtyparam) - @pos - 1)
                        SET @pos = 0
                        SET @cleanloop = 0
                    END
                    
                SET @pos = charindex( '--', UPPER(@dirtyparam)) 
                 IF @pos > 0    
                    BEGIN
                        SET @dirtyparam = LEFT(@dirtyparam,@pos -1 ) + RIGHT(@dirtyparam,LEN(@dirtyparam) - @pos - 1)
                        SET @pos = 0
                        SET @cleanloop = 0
                    END    
                    
                 SET @pos = charindex( '/*', UPPER(@dirtyparam)) 
                     IF @pos > 0    
                        BEGIN
                            SET @dirtyparam = LEFT(@dirtyparam,@pos -1 ) + RIGHT(@dirtyparam,LEN(@dirtyparam) - @pos - 1)
                            SET @pos = 0
                            SET @cleanloop = 0
                        END    
                   SET @pos = charindex( '*/', UPPER(@dirtyparam)) 
                     IF @pos > 0    
                        BEGIN
                            SET @dirtyparam = LEFT(@dirtyparam,@pos -1 ) + RIGHT(@dirtyparam,LEN(@dirtyparam) - @pos - 1)
                            SET @pos = 0
                            SET @cleanloop = 0
                        END         
        END --LOOP
             

      
END



go

GRANT EXECUTE ON dbo.arch_util_sqlinj_cleanser TO REPORTING_APP_ROLE
go
GRANT EXECUTE ON dbo.arch_util_sqlinj_cleanser TO PROVIDER_SUPP_ROLE
go
